### ISSUE TITLE
Add support for arbitrary sorting algorithms via reflection or inheritance

### ISSUE THREAD

**Issue by starwarswii** [w0rthy/ArrayVisualizer#1]
Allow for someone to create another file and have the program automatically recognise and add the sorting algorithm.

This could be done with an interface or abstract algorithm class, or even using carefully designed class files and reflection.

This would allow for the removal of the hard coded switch statements in main and make the code more flexible.

**Comment by w0rthy** [comment]
The code is really old (most of it is from ~2014 as a high school project) and I've just sloppily patched things onto it every now and then. At this point I don't have the dedication to this project anymore to do much more then add visualizations and algorithms infrequently.
