### ISSUE TITLE
Copy my algorithms

### ISSUE THREAD

**Issue by PiotrGrochowski** [w0rthy/ArrayVisualizer#2]
To extend this program, I recommend copying my algorithms and list generator. Make sure to properly convert the scripts to appropriate scripts in your language to prevent bugs.

My visual sorter: https://www.dropbox.com/s/dc535xnkcllpwyk/visualsort.sb2?dl=0 This can only be opened in two programs.
One is online Scratch: https://scratch.mit.edu/projects/editor/?tip_bar=home
The other one is offline Scratch: https://scratch.mit.edu/download

List size is adjustable, with 21 list types available.
There are 11 sorting algorithms: selection sort, insertion sort, bubble sort, cocktail sort, gnome sort, comb sort, shell sort, heap sort, merge sort, quick sort and ternary quick sort.

Text color: yellow
Background color: black
Secondary color: red
Font: Custom Font (download: https://www.dropbox.com/s/x9rpnk33qeurk65/customfont.fon?dl=0)

Details:
Bubble sort, cocktail sort and comb sort when gap size is 1 use an optimization that detects number of last items (and first items in cocktail sort) in place.
Comb sort gap size starts with half list size, then shrinks by ⁴/₃ after each pass (fractional values use floor).
Shell sort gap sequence is Marcin Ciura's gap sequence, extended by multiplying previous term by 2.25 and flooring (1, 4, 10, 23, 57, 132, 301, 701, _1750_, **3937, 8858, 19930**, etc. , apocryphal term is italic, extension is bold).
Heap sort uses bottom-up heapify, and on equal item array it speeds up to O(n).
Merge sort is bottom-up (merges to sets of 2, then 4, 8, etc.).
Quick sort uses random pivot and places it in correct place, then swaps items greater than or equal to pivot in first half to items less than pivot in second half. Identical items is worst case list (O(n²)).
Ternary quick sort uses random pivot and divides the list similar to insertion sort but only moving the first item of =pivot and >pivot categories. Because of ternary division on equal item array it speeds up to O(n). No specific list triggers the worst case performance.﻿

**Comment by w0rthy** [comment]
I appreciate the input but this would not serve to further this project's purpose
